name: Update Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703 # v30
        with:
          nix_conf: |
            accept-flake-config = true

      - name: Update flake.lock
        run: nix flake update

      - name: Run treefmt
        run: nix fmt .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          commit-message: Update dependencies
          branch: ci/update-dependencies
          delete-branch: true
          title: Update dependencies
          labels: dependencies
